@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.overpass.project"
    
    Project <|-- MapOverpassProject
    class MapOverpassProject
    {
        --(constructors)--
        #MapOverpassProject()
        --(collection)--
        +MapOverpassProject get()
    }
    
@enduml

