@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.overpass"
    
    abstract BaseRepeater
    
    BaseRepeater <|-- OverpassDataDownloader
    OverpassDataDownloader --> OsmToPbfConverter : "converts data with"
    OverpassDataDownloader --> OverpassOsmResource : "downloads data with"
    OverpassDataDownloader o-- Folder : "caches data in"
    class OverpassDataDownloader
    {
        --(constructors)--
        +OverpassDataDownloader(Folder)
        --(filesystem)--
        +File osm(String descriptor, Rectangle bounds)
        +File pbf(String baseName, Rectangle bounds)
    }
    
    BaseRepeater <|-- OverpassOsmResource
    OverpassOsmResource --> Folder : "copies data to"
    class OverpassOsmResource
    {
        --(constructors)--
        +OverpassOsmResource(Rectangle)
        --(filesystem)--
        +void safeCopyTo(File destination)
    }
    
@enduml

