@startuml

    !include ../lexakai/lexakai.theme
    
    title "aonia-map-overpass"
    
    artifact kryo
    artifact minlog
    artifact reflectasm
    artifact jackson_annotations
    artifact woodstox_core
    artifact protobuf_java
    artifact aonia_map_data_formats_pbf
    artifact aonia_map_data_library
    artifact aonia_map_geography
    artifact aonia_map_measurements
    artifact aonia_map_overpass
    artifact kivakit_build_metadata
    artifact kivakit_core_collections
    artifact kivakit_core_commandline
    artifact kivakit_core_kernel
    artifact kivakit_core_network_core
    artifact kivakit_core_network_http
    artifact kivakit_core_resource
    artifact kivakit_core_security
    artifact kivakit_core_serialization_core
    artifact kivakit_core_serialization_kryo
    artifact kivakit_core_test
    artifact kivakit_data_compression
    artifact kivakit_data_formats_library
    artifact kivakit_math
    artifact lexakai_annotations
    artifact commons_codec
    artifact commons_logging
    artifact kryo_serializers
    artifact swagger_annotations
    artifact junit
    artifact jpf
    artifact commons_compress
    artifact commons_math
    artifact httpclient
    artifact httpcore
    artifact stax2_api
    artifact hamcrest_core
    artifact annotations
    artifact objenesis
    artifact osmosis_core
    artifact osmosis_osm_binary
    artifact osmosis_pbf
    artifact osmosis_xml
    artifact asm
    artifact spring_beans
    artifact spring_core
    artifact spring_jcl
    artifact spring_jdbc
    artifact spring_tx
    artifact xercesImpl
    aonia_map_data_formats_pbf --> aonia_map_data_library
    aonia_map_data_formats_pbf --> kivakit_data_formats_library
    aonia_map_data_formats_pbf --> osmosis_core
    aonia_map_data_formats_pbf --> osmosis_osm_binary
    aonia_map_data_formats_pbf --> osmosis_pbf
    aonia_map_geography --> aonia_map_measurements
    aonia_map_geography --> kivakit_core_collections
    aonia_map_geography --> kivakit_core_resource
    aonia_map_geography --> kivakit_data_compression
    aonia_map_geography --> kivakit_math
    aonia_map_measurements --> kivakit_core_commandline
    aonia_map_measurements --> kivakit_core_test
    aonia_map_overpass --> aonia_map_data_formats_pbf
    aonia_map_overpass --> aonia_map_geography
    aonia_map_overpass --> kivakit_core_network_http
    aonia_map_overpass --> osmosis_xml
    httpclient --> commons_logging
    httpclient --> httpcore
    junit --> hamcrest_core
    kivakit_core_collections --> kivakit_core_serialization_kryo
    kivakit_core_commandline --> kivakit_core_kernel
    kivakit_core_kernel --> annotations
    kivakit_core_kernel --> jackson_annotations
    kivakit_core_kernel --> junit
    kivakit_core_kernel --> kivakit_build_metadata
    kivakit_core_kernel --> lexakai_annotations
    kivakit_core_kernel --> swagger_annotations
    kivakit_core_network_core --> kivakit_core_security
    kivakit_core_network_http --> httpclient
    kivakit_core_network_http --> kivakit_core_network_core
    kivakit_core_resource --> kivakit_core_serialization_core
    kivakit_core_serialization_kryo --> kryo
    kivakit_core_serialization_kryo --> kryo_serializers
    kivakit_math --> commons_math
    kryo --> minlog
    kryo --> objenesis
    kryo --> reflectasm
    osmosis_core --> commons_compress
    osmosis_core --> jpf
    osmosis_core --> spring_jdbc
    osmosis_core --> stax2_api
    osmosis_core --> woodstox_core
    osmosis_core --> xercesImpl
    osmosis_osm_binary --> protobuf_java
    osmosis_xml --> commons_codec
    reflectasm --> asm
    spring_core --> spring_jcl
    spring_jdbc --> spring_beans
    spring_jdbc --> spring_core
    spring_jdbc --> spring_tx
    
@enduml
