@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.utilities.grid"
    
    interface AsString
    
    class Grid
    {
        --(constructors)--
        +Grid(Angle, Latitude)
        +Grid(Distance, Latitude)
        --
        +GridCell cell(Location)
        --(collection)--
        +Distance approximateCellSize()
        +Count cellCount()
        +List<GridCellIdentifier> cellIdentifiersWithin(Rectangle bounds)
        +Size cellSize()
        +List<GridCell> cells()
        +List<GridCell> cellsIntersecting(Rectangle bounds)
        +List<GridCellIdentifier> identifiers()
        +Count latitudeCellCount()
        +Count longitudeCellCount()
        --(identity)--
        +GridCell cellForIdentifier(GridCellIdentifier)
        +GridCellIdentifier identifierForLocation(Location)
    }
    
    Rectangle <|-- GridCell
    class GridCell
    {
        --(constructors)--
        +GridCell(GridCellIdentifier, Location, Location)
        +GridCell(GridCellIdentifier, Rectangle)
        --
        +String pureRectangleString()
        --(conversion)--
        +String toRectangleString()
        --(identity)--
        +GridCellIdentifier identifier()
        --(naming)--
        +String name()
    }
    
    AsString <|-- GridCellIdentifier
    class GridCellIdentifier
    {
        --(constructors)--
        +GridCellIdentifier()
        +GridCellIdentifier(Grid, int)
        +GridCellIdentifier(Grid, int, int)
        --(collection)--
        +int latitudeIndex()
        +int longitudeIndex()
        --(identity)--
        +int identifier()
    }
    
@enduml

