@startuml

    !include ../lexakai/lexakai.theme
    
    title "aonia-map-utilities-grid"
    
    artifact kryo
    artifact minlog
    artifact reflectasm
    artifact jackson_annotations
    artifact aonia_map_geography
    artifact aonia_map_measurements
    artifact aonia_map_utilities_grid
    artifact kivakit_build_metadata
    artifact kivakit_core_collections
    artifact kivakit_core_commandline
    artifact kivakit_core_kernel
    artifact kivakit_core_resource
    artifact kivakit_core_serialization_core
    artifact kivakit_core_serialization_kryo
    artifact kivakit_core_test
    artifact kivakit_data_compression
    artifact kivakit_math
    artifact lexakai_annotations
    artifact kryo_serializers
    artifact swagger_annotations
    artifact junit
    artifact commons_math
    artifact hamcrest_core
    artifact annotations
    artifact objenesis
    artifact asm
    aonia_map_geography --> aonia_map_measurements
    aonia_map_geography --> kivakit_core_collections
    aonia_map_geography --> kivakit_core_resource
    aonia_map_geography --> kivakit_data_compression
    aonia_map_geography --> kivakit_math
    aonia_map_measurements --> kivakit_core_commandline
    aonia_map_measurements --> kivakit_core_test
    aonia_map_utilities_grid --> aonia_map_geography
    junit --> hamcrest_core
    kivakit_core_collections --> kivakit_core_serialization_kryo
    kivakit_core_commandline --> kivakit_core_kernel
    kivakit_core_kernel --> annotations
    kivakit_core_kernel --> jackson_annotations
    kivakit_core_kernel --> junit
    kivakit_core_kernel --> kivakit_build_metadata
    kivakit_core_kernel --> lexakai_annotations
    kivakit_core_kernel --> swagger_annotations
    kivakit_core_resource --> kivakit_core_serialization_core
    kivakit_core_serialization_kryo --> kryo
    kivakit_core_serialization_kryo --> kryo_serializers
    kivakit_math --> commons_math
    kryo --> minlog
    kryo --> objenesis
    kryo --> reflectasm
    reflectasm --> asm
    
@enduml
