@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.road.model.converters"
    
    abstract BaseStringConverter
    
    BaseStringConverter <|-- DeCartaRoadTypeConverter
    class DeCartaRoadTypeConverter
    {
        --(constructors)--
        +DeCartaRoadTypeConverter(Listener)
    }
    
    BaseStringConverter <|-- DirectionOfTrafficFlowConverter
    class DirectionOfTrafficFlowConverter
    {
        --(constructors)--
        +DirectionOfTrafficFlowConverter(Listener)
    }
    
    BaseStringConverter <|-- RoadNameConverter
    class RoadNameConverter
    {
        --(constructors)--
        +RoadNameConverter(Listener)
    }
    
    BaseStringConverter <|-- RoadShapeConverter
    class RoadShapeConverter
    {
        --(constructors)--
        +RoadShapeConverter(Listener, int)
        --
        +void type(Type)
    }
    
    BaseStringConverter <|-- TrafficDeCartaRoadTypeStringConverter
    class TrafficDeCartaRoadTypeStringConverter
    {
        --(constructors)--
        +TrafficDeCartaRoadTypeStringConverter(Listener)
    }
    
    enum RoadShapeConverter.Type
    {
        DEGREES
        DM5
    }
    
@enduml

