@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.utilities.geohash.project"
    
    Project <|-- MapUtilitiesGeohashProject
    class MapUtilitiesGeohashProject
    {
        --(constructors)--
        #MapUtilitiesGeohashProject()
        --(collection)--
        +MapUtilitiesGeohashProject get()
    }
    
@enduml

