@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.utilities.geojson.project"
    
    Project <|-- MapUtilitiesGeoJsonProject
    class MapUtilitiesGeoJsonProject
    {
        --(constructors)--
        #MapUtilitiesGeoJsonProject()
        --(collection)--
        +MapUtilitiesGeoJsonProject get()
    }
    
@enduml

