@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.geography.shape.polyline.compression.differential"
    
    Polyline <|-- CompressedPolyline
    class CompressedPolyline
    {
        --(constructors)--
        #CompressedPolyline()
        --
        +Polyline decompress()
        +long[] decompressedInDecimal()
        +CompressedPolyline fromLocationSequence(Location... locations)
        +CompressedPolyline fromLocationSequence(Iterable<Location> locations)
        +CompressedPolyline fromLocationSequence(LocationSequence)
        +void main(String[] args)
        --(collection)--
        +ByteList asBytes()
        +BitArray compress(Iterable<Location> locations)
        +CompressedPolyline fromBitArray(BitArray bits)
    }
    
    class CompressedPolyline.Encoding
    {
        --(constructors)--
        +Encoding(int)
        --
        +int bits()
        --(math)--
        +long maximumLatitudeOffset()
        +long maximumLongitudeOffset()
        +long minimumLatitudeOffset()
        +long minimumLongitudeOffset()
    }
    
    enum CompressedPolyline.Proximity
    {
        DISTANCE1
        DISTANCE2
        DISTANCE3
        DISTANCE4
        DISTANCE5
        DISTANCE6
        DISTANCE7
        DISTANCE8
    }
    
@enduml

