@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.geography.shape"
    
    enum Outline.Containment
    {
        INDETERMINATE
        INSIDE
        ON_BORDER
        OUTSIDE
    }
    
    interface Outline
    {
        --
        +Containment containment(Location)
        --(collection)--
        +boolean contains(Located)
        +boolean contains(Location)
    }
    
    interface Outline
    Outline <|-- Shape
    interface Shape
    {
    }
    
@enduml

