@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.geography.indexing.quadtree"
    
    abstract BaseIterator
    
    BaseIterator <|-- QuadTreeSpatialIndex.Quadrant.BoundedLeafIterator
    class QuadTreeSpatialIndex.Quadrant.BoundedLeafIterator
    {
    }
    
    class QuadTreeSpatialIndex<Element>
    {
        --(constructors)--
        +QuadTreeSpatialIndex()
        +QuadTreeSpatialIndex(int, Distance)
        --
        +Rectangle bounds()
        +void dump(PrintStream out)
        +boolean replace(Element oldValue, Element newValue)
        --(collection)--
        +void add(Element object)
        +void addAll(Iterable<Element> objects)
        +void clear()
        +Count count()
        +Iterator<Element> inside(Rectangle bounds, Matcher<Element>)
        +Iterator<Element> inside(Rectangle bounds)
        +void remove(Element object)
        +void removeAll(Rectangle bounds, Matcher<Element>)
        +int size()
    }
    
    class QuadTreeSpatialIndex.Quadrant
    {
        --(constructors)--
        #Quadrant()
    }
    
    BaseIterator <|-- QuadTreeSpatialIndex.Quadrant.QuadrantIterator
    class QuadTreeSpatialIndex.Quadrant.QuadrantIterator
    {
    }
    
@enduml

