@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.geography.project"
    
    KryoTypes <|-- MapGeographyKryoTypes
    class MapGeographyKryoTypes
    {
        --(constructors)--
        +MapGeographyKryoTypes()
    }
    
    class MapGeographyLimits
    {
    }
    
    Project <|-- MapGeographyProject
    class MapGeographyProject
    {
        --(constructors)--
        #MapGeographyProject()
        --
        +KryoTypes kryoTypes()
        --(collection)--
        +MapGeographyProject get()
    }
    
    MapMeasurementsRandomValueFactory <|-- MapGeographyRandomValueFactory
    class MapGeographyRandomValueFactory
    {
        --(constructors)--
        +MapGeographyRandomValueFactory()
        +MapGeographyRandomValueFactory(long)
        --(factory)--
        +Latitude newLatitude(Latitude min, Latitude max)
        +Latitude newLatitude()
        +Location newLocation()
        +Location newLocation(Rectangle bounds)
        +Longitude newLongitude()
        +Longitude newLongitude(Longitude min, Longitude max)
        +Rectangle newRectangle(Rectangle bounds)
        +Rectangle newRectangle()
        +Rectangle newRectangle(Rectangle bounds, Distance maximumRadius)
        +Size newSize(Size maximum)
        +Size newSize(Size min, Size max)
    }
    
    MapMeasurementsUnitTest <|-- MapGeographyUnitTest
    class MapGeographyUnitTest
    {
        --
        #Location location(double latitude, double longitude)
        #Rectangle rectangle(String rectangle)
    }
    
@enduml

