@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.ui.swing.map.graphics.canvas"
    
    class MapCanvas
    {
        --(constructors)--
        +MapCanvas(Graphics2D, Rectangle, Scale, CoordinateMapper)
        --
        +float awtDistance(Distance)
        +Point2D awtPoint(Location)
        +java.awt.Rectangle awtRectangle(Rectangle)
        +Rectangle bounds()
        +Distance distance(float pixels)
        +Shape drawArrow(Style, Location, Distance size, Heading)
        +Shape drawDot(Style, Width, Style outlineStyle, Width outlineWidth, Location)
        +Rectangle2D drawLabel(Style, Location, Width strokeWidth, String text)
        +void drawLabeledRectangle(Style, Width, Rectangle, String text)
        +Shape drawPolyline(Style, Width, Style outlineStyle, Width outlineWidth, Polyline)
        +Graphics2D graphics()
        +Rectangle2D labelBounds(Style, Location, String text)
        +Location location(Point2D)
        +Rectangle rectangle(java.awt.Rectangle bounds)
        +Scale scale()
        +Distance viewWidth()
    }
    
    enum Width.Metric
    {
        DISTANCE
        PIXELS
    }
    
    enum Scale
    {
        CITY
        NEIGHBORHOOD
        REGION
        STATE
        STREET
    }
    
    class Stroke
    {
        --(constructors)--
        +Stroke(Stroke)
        +Stroke(int, int)
        +Stroke(int, int, float, float[], float)
        --
        +void apply(MapCanvas, Width)
        --(functional)--
        +Shape strokedShape(MapCanvas, Width, Shape)
    }
    
    class Style
    {
        --(constructors)--
        +Style()
        --
        +void applyDraw(MapCanvas, Width)
        +void applyFill(MapCanvas, Width)
        +Color draw()
        +Stroke drawStroke()
        +Color fill()
        +Stroke fillStroke()
        +Font font()
        +FontMetrics fontMetrics(MapCanvas)
        +Shape shape(MapCanvas, Width, Shape)
        +Shape shape(MapCanvas, Shape)
        +Color text()
        +void text(MapCanvas)
        +Rectangle2D textBounds(MapCanvas, String text)
        --(functional)--
        +Style darkened(Percent)
        +Style darkened()
        +Style lightened(Percent)
        +Style lightened()
        +Style withDrawColor(Color)
        +Style withDrawStroke(Stroke)
        +Style withFillColor(Color fill)
        +Style withFillStroke(Stroke)
        +Style withFont(Font)
        +Style withFontSize(int size)
        +Style withTextColor(Color text)
    }
    
    class Width
    {
        --
        +Width of(Distance)
        +Width pixels(Float pixels)
        --(conversion)--
        +Distance asDistance(MapCanvas)
        +float asPixels(MapCanvas)
        --(distance)--
        +Width meters(double meters)
        --(functional)--
        +Width fattened(Percent)
        --(math)--
        +Width minus(MapCanvas, Width that)
        +Width plus(MapCanvas, Width that)
        +Width times(Percent scaleFactor)
    }
    
@enduml

