@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.ui.swing.debug"
    
    interface Drawable
    {
        --
        +void draw(DrawingSurface)
    }
    
    interface DrawingSurface
    {
        --
        +void draw(Polyline, Color background, Color foreground, String label)
        +void draw(Location, Color background, Color foreground, String label)
    }
    
    interface DrawingSurface
    DrawingSurface <|-- InteractiveDrawingSurface
    interface InteractiveDrawingSurface
    {
        --
        +void highlight(boolean highlight)
        +void highlightColor(Color)
        +Shape hitTestShape()
    }
    
    interface View
    View <|-- InteractiveView
    interface InteractiveView
    {
        --
        +void frameComplete()
        +void frameSpeed(Duration delay)
        +void pullToFront(ViewableIdentifier)
        +void zoomTo(Rectangle bounds)
        +void zoomToContents(Percent margin)
        --(collection)--
        +void pushToBack(ViewableIdentifier)
    }
    
    interface Named
    Named <|-- View
    interface View
    {
        --
        +void update(ViewableIdentifier, Viewable object)
        --(collection)--
        +void add(Viewable object)
        +void clear()
        +void remove(ViewableIdentifier)
    }
    
    interface Bounded
    interface Drawable
    Bounded <|-- Viewable
    Drawable <|-- Viewable
    interface Viewable
    {
    }
    
    class ViewableIdentifier
    {
        --(constructors)--
        +ViewableIdentifier(Object)
    }
    
    interface Viewer
    {
        --
        +View view(String name)
        +Collection<View> views()
    }
    
@enduml

