@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.ui.swing.debug.debuggers.indexing.rtree"
    
    interface RTreeSpatialIndexDebugger
    
    RTreeSpatialIndexDebugger <|-- VisualRTreeSpatialIndexDebugger
    class VisualRTreeSpatialIndexDebugger<T>
    {
        --
        +void updateElementInView(Leaf<T>, T element)
        +void updateNodeInView(Node<T>)
        +void viewer(Viewer)
        --(collection)--
        +void removeNodeFromView(Node<T>)
    }
    
@enduml

