@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.ui.swing.debug.viewer"
    
    interface Iterator
    interface Viewer
    
    Viewer <|-- BaseViewer
    abstract class BaseViewer
    {
        --(factory)--
        #View newView(String name)
    }
    
    Iterator <|-- ColorSequence
    class ColorSequence
    {
    }
    
    class ViewableMap.Entry
    {
        --(constructors)--
        +Entry(ViewableIdentifier, Viewable)
        --
        +void outline(Shape outline)
        +void viewable(Viewable)
    }
    
    class ViewableMap
    {
        --
        +Rectangle bounds()
        +void draw(DrawingSurface)
        +void pullToFront(ViewableIdentifier)
        +void select(Point)
        +void update(ViewableIdentifier, Viewable)
        --(collection)--
        +void add(Viewable)
        +void clear()
        +void pushToBack(ViewableIdentifier)
        +void remove(ViewableIdentifier)
    }
    
@enduml

