@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.ui.swing.map.coordinates.projections"
    
    interface CoordinateMapper
    
    CoordinateMapper <|-- SphericalMercatorProjection
    class SphericalMercatorProjection
    {
        --(constructors)--
        +SphericalMercatorProjection(Dimension)
    }
    
@enduml

