open module tdk.graph.core
{
    requires transitive java.sql;

    requires transitive tdk.core.data;
    requires transitive tdk.core.utilities;
    requires transitive tdk.data.formats.pbf;
    requires transitive tdk.map.region;
    requires transitive tdk.map.overpass;
    requires transitive tdk.map.ui;
    requires transitive tdk.map.road.name.standardizer;
    requires transitive tdk.map.geography;
    requires transitive tdk.graph.traffic;

    exports com.telenav.tdk.graph.analytics.classification.classifiers.road;
    exports com.telenav.tdk.graph.analytics.classification.classifiers.signpost;
    exports com.telenav.tdk.graph.analytics.classification.classifiers.turn;
    exports com.telenav.tdk.graph.analytics.classification;
    exports com.telenav.tdk.graph.analytics.crawler;
    exports com.telenav.tdk.graph.analytics.junction;
    exports com.telenav.tdk.graph.analytics.ramp;
    exports com.telenav.tdk.graph.collections;
    exports com.telenav.tdk.graph.identifiers.collections;
    exports com.telenav.tdk.graph.identifiers;
    exports com.telenav.tdk.graph.io.archive;
    exports com.telenav.tdk.graph.io.convert;
    exports com.telenav.tdk.graph.io.load.loaders.decimation;
    exports com.telenav.tdk.graph.io.load.loaders.region.regions;
    exports com.telenav.tdk.graph.io.load.loaders.region;
    exports com.telenav.tdk.graph.io.load.loaders;
    exports com.telenav.tdk.graph.io.load;
    exports com.telenav.tdk.graph.io.save;
    exports com.telenav.tdk.graph.library.osm.change;
    exports com.telenav.tdk.graph.map;
    exports com.telenav.tdk.graph.matching.conflation;
    exports com.telenav.tdk.graph.matching.snapping;
    exports com.telenav.tdk.graph.metadata;
    exports com.telenav.tdk.graph.navigation.limiters;
    exports com.telenav.tdk.graph.navigation.navigators;
    exports com.telenav.tdk.graph.navigation;
    exports com.telenav.tdk.graph.project;
    exports com.telenav.tdk.graph.relations.restrictions;
    exports com.telenav.tdk.graph.specifications.common.edge.store;
    exports com.telenav.tdk.graph.specifications.common.edge;
    exports com.telenav.tdk.graph.specifications.common.element;
    exports com.telenav.tdk.graph.specifications.common.graph.loader;
    exports com.telenav.tdk.graph.specifications.common.node.store;
    exports com.telenav.tdk.graph.specifications.common.node;
    exports com.telenav.tdk.graph.specifications.common.place.store;
    exports com.telenav.tdk.graph.specifications.common.place;
    exports com.telenav.tdk.graph.specifications.common.relation.store;
    exports com.telenav.tdk.graph.specifications.common.relation;
    exports com.telenav.tdk.graph.specifications.common.shapepoint.store;
    exports com.telenav.tdk.graph.specifications.common.shapepoint;
    exports com.telenav.tdk.graph.specifications.common.vertex.store;
    exports com.telenav.tdk.graph.specifications.common.vertex;
    exports com.telenav.tdk.graph.specifications.common;
    exports com.telenav.tdk.graph.specifications.library.attributes;
    exports com.telenav.tdk.graph.specifications.library.pbf;
    exports com.telenav.tdk.graph.specifications.library.properties;
    exports com.telenav.tdk.graph.specifications.library.store;
    exports com.telenav.tdk.graph.specifications.osm.graph.converter;
    exports com.telenav.tdk.graph.specifications.osm.graph.edge.model.attributes;
    exports com.telenav.tdk.graph.specifications.osm.graph.edge.model;
    exports com.telenav.tdk.graph.specifications.osm.graph.edge.store;
    exports com.telenav.tdk.graph.specifications.osm.graph.loader;
    exports com.telenav.tdk.graph.specifications.osm.graph;
    exports com.telenav.tdk.graph.specifications.osm;
    exports com.telenav.tdk.graph.specifications.unidb.graph.converter;
    exports com.telenav.tdk.graph.specifications.unidb.graph.edge.model.attributes;
    exports com.telenav.tdk.graph.specifications.unidb.graph.edge.model;
    exports com.telenav.tdk.graph.specifications.unidb.graph.edge.store;
    exports com.telenav.tdk.graph.specifications.unidb.graph.loader;
    exports com.telenav.tdk.graph.specifications.unidb.graph.vertex;
    exports com.telenav.tdk.graph.specifications.unidb.graph;
    exports com.telenav.tdk.graph.specifications.unidb;
    exports com.telenav.tdk.graph.ui.debuggers.edge.sectioner;
    exports com.telenav.tdk.graph.ui.viewer;
    exports com.telenav.tdk.graph;
}
