@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.cutter"
    
    abstract class Cut
    {
        --(constructors)--
        #Cut(PbfRegionCutter)
        --
        +Set<Resource> cut()
    }
    
    PbfRegionCutter --> Cut : "cuts with"
    PbfRegionCutter o-- WayFilter : "filters ways with"
    PbfRegionCutter o-- RegionSet : "regions to extract"
    class PbfRegionCutter
    {
        --(constructors)--
        +PbfRegionCutter(Source<PbfDataSource>, Folder, WayFilter)
        --
        +void regionsToExtract(RegionSet regionsToExtract)
        --cutting--
        +ResourceList cut()
    }
    
@enduml

