@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.cutter.project"
    
    Project <|-- MapCutterProject
    class MapCutterProject
    {
        --(constructors)--
        #MapCutterProject()
        --(collection)--
        +MapCutterProject get()
    }
    
@enduml

