@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.cutter.cuts"
    
    Cut <|-- FastCut
    class FastCut
    {
        --(constructors)--
        +FastCut(PbfRegionCutter, RegionWays)
    }
    
    Cut <|-- SoftCut
    class SoftCut
    {
        --(constructors)--
        +SoftCut(PbfRegionCutter, RegionNodes, RegionWays)
    }
    
@enduml

