@startuml

    !include ../lexakai/lexakai.theme
    
    title "Map Cutter"
    
    abstract class Cut
    {
        --(constructors)--
        #Cut(PbfRegionCutter)
        --
        +Set<Resource> cut()
    }
    
    Cut <|-- FastCut
    class FastCut
    {
        --(constructors)--
        +FastCut(PbfRegionCutter, RegionWays)
    }
    
    PbfRegionCutter --> Cut : "cuts with"
    PbfRegionCutter o-- WayFilter : "filters ways with"
    PbfRegionCutter o-- RegionSet : "regions to extract"
    class PbfRegionCutter
    {
        --(constructors)--
        +PbfRegionCutter(Source<PbfDataSource>, Folder, WayFilter)
        --
        +void regionsToExtract(RegionSet regionsToExtract)
        --cutting--
        +ResourceList cut()
    }
    
    Cut <|-- SoftCut
    class SoftCut
    {
        --(constructors)--
        +SoftCut(PbfRegionCutter, RegionNodes, RegionWays)
    }
    
@enduml

