@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.road.name.standardizer"
    
    interface RoadNameStandardizer
    
    RoadNameStandardizer <|-- BaseRoadNameStandardizer
    abstract class BaseRoadNameStandardizer
    {
    }
    
    enum RoadNameStandardizer.Mode
    {
        AONIA_STANDARDIZATION
        NO_STANDARDIZATION
    }
    
    interface RoadNameStandardizer
    {
        --
        +void mode(Mode)
        --(naming)--
        +RoadNameStandardizer get(MapLocale, Mode)
        +ParsedRoadName standardize(RoadName)
        --(read)--
        +void loadInBackground(MapLocale, Mode)
    }
    
@enduml

