@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.region.locale"
    
    class HascCode
    {
        --
        +String code()
        +Country country()
        +State state()
        --(parsing)--
        +HascCode parse(String code)
    }
    
    Locale <|-- MapLocale
    class MapLocale
    {
        --(constructors)--
        +MapLocale(Country)
        +MapLocale(Region<?>, LanguageIsoCode)
        --
        +T create(PackagePath, String suffix)
        +Region<?> region()
    }
    
@enduml

