@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.region.project"
    
    class MapRegionLimits.Estimated
    {
    }
    
    class MapRegionLimits.Limit
    {
    }
    
    KryoTypes <|-- MapRegionKryoTypes
    class MapRegionKryoTypes
    {
        --(constructors)--
        +MapRegionKryoTypes()
    }
    
    class MapRegionLimits
    {
    }
    
    Project <|-- MapRegionProject
    class MapRegionProject
    {
        --(constructors)--
        #MapRegionProject()
        --(collection)--
        +Folder aoniaMapFolder()
        +MapRegionProject get()
        --(identity)--
        +Version borderDataVersion()
        --(serialization)--
        +SerializationSessionFactory sessionFactory()
    }
    
    MapGeographyUnitTest <|-- MapRegionUnitTest
    class MapRegionUnitTest
    {
        --(constructors)--
        +MapRegionUnitTest()
        --
        #RegionCode code(String)
    }
    
@enduml

