@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.road.name.parser.locales.indonesian"
    
    abstract BaseRoadNameParser
    
    enum IndonesianRoadNameParser.Capitalization
    {
        CAPITALIZED
        LOWERCASE
        UPPERCASE
    }
    
    BaseRoadNameParser <|-- IndonesianRoadNameParser
    class IndonesianRoadNameParser
    {
    }
    
    Tokenizer <|-- IndonesianTokenizer
    class IndonesianTokenizer
    {
        --(checks)--
        +boolean isCardinalDirection(Token)
        +boolean isCloseParenthesis(Token)
        +boolean isDigit(Token)
        +boolean isOctant(Token)
        +boolean isOpenParenthesis(Token)
        +boolean isProperName(Token)
        +boolean isQuadrant(Token)
        +boolean isRoadType(Token)
        +boolean isRomanNumeral(Token)
    }
    
@enduml

