@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.road.name.parser.tokenizer.symbols"
    
    interface Iterable
    
    class Symbol
    {
        --
        +Symbol of(String value)
        +String text()
        --(naming)--
        +String name()
    }
    
    Iterable <|-- SymbolList
    class SymbolList
    {
        --(constructors)--
        +SymbolList()
        +SymbolList(List<Symbol>)
        --
        +Symbol get(int index)
        --(collection)--
        +Symbol first()
        +boolean isEmpty()
        +SymbolList of(String input)
        +int size()
        +SymbolList subList(int from)
        --(conversion)--
        +SymbolStream asStream()
    }
    
    class SymbolStream
    {
        --
        +void advance(int count)
        +int at()
        +void at(int at)
        +Symbol current()
        +String currentText()
        +boolean lookingAt(Symbol... symbols)
        +boolean lookingAt(String... symbols)
        +boolean lookingAtDigit()
        +boolean lookingAtWhiteSpace()
        +boolean matches(Symbol... symbols)
        +boolean matches(String... symbols)
        +void skipAny(Symbol)
        +void skipAny(String... symbols)
        +void skipAnyWhiteSpace()
        +String text()
        --(collection)--
        +Symbol first()
        --(iteration)--
        +boolean hasMore()
        +void next()
    }
    
    Symbol <|-- Word
    class Word
    {
    }
    
@enduml

