@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.aonia.map.road.name.parser.project"
    
    Project <|-- MapRoadNameParserProject
    class MapRoadNameParserProject
    {
        --(constructors)--
        #MapRoadNameParserProject()
        --(collection)--
        +MapRoadNameParserProject get()
    }
    
@enduml

